language: python

python:
    - "2.7"
    - "2.6"
    - "pypy"
# Don't understand why python 3.3 build is failing
#    - "3.3"

install:
  - pip install --use-mirrors -r requirements.txt
  - pip install --use-mirrors -r test-requirements.txt
  - python setup.py install

script:
  - pep8 --ignore=E501 src/*.py
  - pylint --rcfile=pylintrc src/*.py
